name: Test Prod Chat Version
on: push
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install npm deps
        working-directory: .
        run: npm ci
      - name: Build app
        working-directory: .
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
